version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: haliverse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: haliverse_db
    ports:
      - "5432:5432"
    volumes:
      - haliverse_postgres_data:/var/lib/postgresql/data

volumes:
  haliverse_postgres_data:
